list: $/branmuffin/spa/models/categories/columns.yaml
modelClass: Branmuffin\Spa\Models\Categories
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'branmuffin/spa/categories/update/:id'
