list: $/branmuffin/spa/models/pages/columns.yaml
modelClass: Branmuffin\Spa\Models\Pages
title: Pages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'branmuffin/spa/pages/update/:id'
